apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 879786009908.dkr.ecr.us-east-1.amazonaws.com/automated-backend:1.0
          ports:
            - containerPort: 5000