apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 879786009908.dkr.ecr.us-east-1.amazonaws.com/automated-backend:8c77d2ab2e124ff818fa9f7c8412d6efe929df91
          ports:
            - containerPort: 5000