apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 879786009908.dkr.ecr.us-east-1.amazonaws.com/automated-frontend:1.0
          ports:
            - containerPort: 8080