apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 879786009908.dkr.ecr.us-east-1.amazonaws.com/automated-frontend:89ec0b72424cd267e87f975da8c3b6d898a5aa84
          ports:
            - containerPort: 8080